<?php

namespace AppBundle\Repository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCryptos($currencies)
	{
		return $this->createQueryBuilder('currency')
			->andWhere('currency.name = :currencies' )
			->leftJoin('currency.crypto_currency', 'cc')
			->addSelect('cc')
			->setParameter('currencies', $currencies)
			->getQuery();
			//->execute();
		  //  ->getArrayResult();
	}

	public function findAllQueryBuilder($currency)
	{
		return $this->createQueryBuilder('currency')
			->andWhere('currency.name = :name' )
			->leftJoin('currency.crypto_currency', 'c')
			->addSelect('c')
			->setParameter('name', $currency);
	}


	public function findAllQueryBuilder1($currency)
	{
		return $this->createQueryBuilder('currency')
			->andWhere('currency.name = :name' )
			->setParameter('name', $currency);
	}


}
