<?php

namespace AppBundle\Repository;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserByConfirmationToken($token)
    {
        return $this->createQueryBuilder('user')
            ->andwhere('user.token = :token')
            ->setParameter('token', $token)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function getUserAndVideos($user_slug)
    {
        return $this->createQueryBuilder('user')
            ->andwhere('user.slug = :slug')
            ->andWhere('vid.status = :status' )
            ->setParameter('status', 1)
            ->setParameter('slug', $user_slug)
            ->leftJoin('user.videos', 'vid')
            ->addSelect('vid')
            ->getQuery()
            ->execute();
    }

    public function getUserAndVideosPaginated($user_slug,$offset ,$maxResults)
    {
        return $this->createQueryBuilder('user')
            ->andwhere('user.slug = :slug')
            ->andWhere('vid.status = :status' )
            ->setParameter('status', 1)
            ->setParameter('slug', $user_slug)
            ->leftJoin('user.videos', 'vid')
            ->setFirstResult($offset)
            ->setMaxResults($maxResults)
            ->addSelect('vid')
            ->getQuery()
            ->execute();
    }
}
